# Minimal Jupyter Book config
title: Computational Methods (WiSe 2025/2026)
author: Stefan Endres & Lutz MÃ¤dler
only_build_toc_files: true          # only the notebooks listed in _toc.yml
repository:
  url: https://github.com/Leibniz-IWT/comp_eng
  path_to_book: .
  branch: main
html:
  favicon: images/favicon.ico
  use_repository_button: true
  use_binder_button: true           # shows â€œlaunch ğŸš€â€ badge automatically
  extra_footer: |
    Â© 2025 University of Bremen. Released under CC-BY-4.0.
launch_buttons:
  binderhub_url: https://mybinder.org
