name: compeng
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - sympy
  - gymnasium
  - pip
  - pip:
      #- jupyter-book>=1.0.0
      - jupyter-book<2.0
      - stable-baselines3